# Default values for intake-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: dpeterk/intake-server
  pullPolicy: IfNotPresent

imagePullSecrets: []

containers:
  volumeMounts: []

extraEnv:
  catalogPath:
    name: INTAKE_PATH
    value: ""
  serverPort:
    name: INTAKE_PORT
    value: 5000

extraVolumes: []

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

resources: {}

nodeSelector: {}
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
terminationGracePeriodSeconds: 30
tolerations: []
affinity: {}
