# Default values for intake-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: dpeterk/intake-server
  pullPolicy: IfNotPresent

containers:
  env:
  - name: INTAKE_PATH
    value: ""
  - name: INTAKE_PORT
    value: ""
  volumeMounts: []

extraVolumes: []

imagePullSecrets: []

serviceAccount:
  create: false

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: ""

ingress:
  enabled: false

resources: {}

nodeSelector: {}
dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
terminationGracePeriodSeconds: 30
tolerations: []
affinity: {}
